main: tp.mike.TestPlugin
version: 1.0.1
name: TestPlugin
author: Mike
api-version: 1.21

commands:
  TestPlugin:
    desciption: principal commands for the TestPlugin
    aliases: 
      - mp
  exp:
    desciption: the command /exp give you xp
  fly:
    desciption: the command /fly gives you the ability to fly
  menu:
    desciption: the command /menu is the main menu command

